### PR TITLE
Ft/versioning

### PR DESCRIPTION
**Pull request by Elfinalist**
#### What does this PR do?
Fix versioning problem

#### Description of Task to be completed?
implement separate versioning for challenge 3 from challenge 2.

#### How should this be manually tested?
Run the app using `python app.py`
Run tests using `pytest`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164070418

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by petermwash — CHANGES_REQUESTED** [review]
Hey, Kindly add all the `.DS_Store ` files into the `.gitignore` file then ping me to review it again. otherwise good job here.

**Comment by petermwash** [comment]
Also, your Travis is failing, any reasons for that?

**Comment by Elfinalist** [comment]
Hey @petermwash I forgot to pass the testing config while instantiating the app in the conftest.py thats why travis was failing. I have now fixed it.

**Review by petermwash — APPROVED** [review]
LGTM.

**Comment by Elfinalist** [comment]
Thank you.

**Pull request merged**
